# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgencodingfixerbase.ui'
#
# Created: Sun Mar  3 21:12:46 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_EncodingFixerDialogBase(object):
    def setupUi(self, EncodingFixerDialogBase):
        EncodingFixerDialogBase.setObjectName(_fromUtf8("EncodingFixerDialogBase"))
        EncodingFixerDialogBase.resize(548, 409)
        EncodingFixerDialogBase.setMinimumSize(QtCore.QSize(540, 400))
        EncodingFixerDialogBase.setMaximumSize(QtCore.QSize(600, 550))
        EncodingFixerDialogBase.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/shapefile_encoding_fixer/encoding_fixer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EncodingFixerDialogBase.setWindowIcon(icon)
        EncodingFixerDialogBase.setWhatsThis(_fromUtf8(""))
        self.gridLayout_4 = QtGui.QGridLayout(EncodingFixerDialogBase)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(EncodingFixerDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.groupInfo = QtGui.QGroupBox(EncodingFixerDialogBase)
        self.groupInfo.setObjectName(_fromUtf8("groupInfo"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupInfo)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelInfo1 = QtGui.QLabel(self.groupInfo)
        self.labelInfo1.setObjectName(_fromUtf8("labelInfo1"))
        self.gridLayout_2.addWidget(self.labelInfo1, 0, 0, 1, 1)
        self.labelInfo2 = QtGui.QLabel(self.groupInfo)
        self.labelInfo2.setObjectName(_fromUtf8("labelInfo2"))
        self.gridLayout_2.addWidget(self.labelInfo2, 1, 0, 1, 1)
        self.labelFile = QtGui.QLabel(self.groupInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFile.sizePolicy().hasHeightForWidth())
        self.labelFile.setSizePolicy(sizePolicy)
        self.labelFile.setObjectName(_fromUtf8("labelFile"))
        self.gridLayout_2.addWidget(self.labelFile, 0, 1, 1, 1)
        self.labelInfo3 = QtGui.QLabel(self.groupInfo)
        self.labelInfo3.setObjectName(_fromUtf8("labelInfo3"))
        self.gridLayout_2.addWidget(self.labelInfo3, 2, 0, 1, 1)
        self.labelLDID = QtGui.QLabel(self.groupInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLDID.sizePolicy().hasHeightForWidth())
        self.labelLDID.setSizePolicy(sizePolicy)
        self.labelLDID.setObjectName(_fromUtf8("labelLDID"))
        self.gridLayout_2.addWidget(self.labelLDID, 1, 1, 1, 1)
        self.labelCPG = QtGui.QLabel(self.groupInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCPG.sizePolicy().hasHeightForWidth())
        self.labelCPG.setSizePolicy(sizePolicy)
        self.labelCPG.setObjectName(_fromUtf8("labelCPG"))
        self.gridLayout_2.addWidget(self.labelCPG, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupInfo, 1, 0, 1, 4)
        self.buttonFile = QtGui.QPushButton(EncodingFixerDialogBase)
        self.buttonFile.setMinimumSize(QtCore.QSize(48, 0))
        self.buttonFile.setObjectName(_fromUtf8("buttonFile"))
        self.gridLayout.addWidget(self.buttonFile, 0, 3, 1, 1)
        self.comboLayer = QtGui.QComboBox(EncodingFixerDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboLayer.sizePolicy().hasHeightForWidth())
        self.comboLayer.setSizePolicy(sizePolicy)
        self.comboLayer.setMinimumSize(QtCore.QSize(220, 0))
        self.comboLayer.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.comboLayer.setObjectName(_fromUtf8("comboLayer"))
        self.gridLayout.addWidget(self.comboLayer, 0, 2, 1, 1)
        self.groupFix = QtGui.QGroupBox(EncodingFixerDialogBase)
        self.groupFix.setObjectName(_fromUtf8("groupFix"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupFix)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 5, 0, 1, 2)
        self.labelMethodDescription = QtGui.QLabel(self.groupFix)
        self.labelMethodDescription.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMethodDescription.sizePolicy().hasHeightForWidth())
        self.labelMethodDescription.setSizePolicy(sizePolicy)
        self.labelMethodDescription.setWordWrap(True)
        self.labelMethodDescription.setOpenExternalLinks(True)
        self.labelMethodDescription.setObjectName(_fromUtf8("labelMethodDescription"))
        self.gridLayout_3.addWidget(self.labelMethodDescription, 4, 0, 1, 2)
        self.radioSetLDID = QtGui.QRadioButton(self.groupFix)
        self.radioSetLDID.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioSetLDID.sizePolicy().hasHeightForWidth())
        self.radioSetLDID.setSizePolicy(sizePolicy)
        self.radioSetLDID.setObjectName(_fromUtf8("radioSetLDID"))
        self.gridLayout_3.addWidget(self.radioSetLDID, 1, 0, 1, 1)
        self.comboEncodingLDID = QtGui.QComboBox(self.groupFix)
        self.comboEncodingLDID.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboEncodingLDID.sizePolicy().hasHeightForWidth())
        self.comboEncodingLDID.setSizePolicy(sizePolicy)
        self.comboEncodingLDID.setEditable(False)
        self.comboEncodingLDID.setObjectName(_fromUtf8("comboEncodingLDID"))
        self.gridLayout_3.addWidget(self.comboEncodingLDID, 1, 1, 1, 1)
        self.radioSetCPG = QtGui.QRadioButton(self.groupFix)
        self.radioSetCPG.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioSetCPG.sizePolicy().hasHeightForWidth())
        self.radioSetCPG.setSizePolicy(sizePolicy)
        self.radioSetCPG.setObjectName(_fromUtf8("radioSetCPG"))
        self.gridLayout_3.addWidget(self.radioSetCPG, 2, 0, 1, 1)
        self.comboEncodingCPG = QtGui.QComboBox(self.groupFix)
        self.comboEncodingCPG.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboEncodingCPG.sizePolicy().hasHeightForWidth())
        self.comboEncodingCPG.setSizePolicy(sizePolicy)
        self.comboEncodingCPG.setObjectName(_fromUtf8("comboEncodingCPG"))
        self.gridLayout_3.addWidget(self.comboEncodingCPG, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(self.groupFix)
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 6, 0, 1, 2)
        self.radioClearLDID = QtGui.QRadioButton(self.groupFix)
        self.radioClearLDID.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioClearLDID.sizePolicy().hasHeightForWidth())
        self.radioClearLDID.setSizePolicy(sizePolicy)
        self.radioClearLDID.setObjectName(_fromUtf8("radioClearLDID"))
        self.gridLayout_3.addWidget(self.radioClearLDID, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.groupFix, 2, 0, 1, 4)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.label.setBuddy(self.comboLayer)

        self.retranslateUi(EncodingFixerDialogBase)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), EncodingFixerDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(EncodingFixerDialogBase)
        EncodingFixerDialogBase.setTabOrder(self.comboLayer, self.buttonFile)
        EncodingFixerDialogBase.setTabOrder(self.buttonFile, self.radioClearLDID)
        EncodingFixerDialogBase.setTabOrder(self.radioClearLDID, self.radioSetLDID)
        EncodingFixerDialogBase.setTabOrder(self.radioSetLDID, self.comboEncodingLDID)
        EncodingFixerDialogBase.setTabOrder(self.comboEncodingLDID, self.radioSetCPG)
        EncodingFixerDialogBase.setTabOrder(self.radioSetCPG, self.comboEncodingCPG)

    def retranslateUi(self, EncodingFixerDialogBase):
        EncodingFixerDialogBase.setWindowTitle(QtGui.QApplication.translate("EncodingFixerDialogBase", "Fix Shapefile Encoding", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("EncodingFixerDialogBase", "Shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.groupInfo.setTitle(QtGui.QApplication.translate("EncodingFixerDialogBase", "Layer info", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo1.setText(QtGui.QApplication.translate("EncodingFixerDialogBase", "Dbf File:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo2.setText(QtGui.QApplication.translate("EncodingFixerDialogBase", "LDID byte:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFile.setText(QtGui.QApplication.translate("EncodingFixerDialogBase", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo3.setText(QtGui.QApplication.translate("EncodingFixerDialogBase", "CPG file:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLDID.setText(QtGui.QApplication.translate("EncodingFixerDialogBase", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCPG.setText(QtGui.QApplication.translate("EncodingFixerDialogBase", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFile.setText(QtGui.QApplication.translate("EncodingFixerDialogBase", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupFix.setTitle(QtGui.QApplication.translate("EncodingFixerDialogBase", "Fix encoding declaration", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMethodDescription.setText(QtGui.QApplication.translate("EncodingFixerDialogBase", "Description placeholder...", None, QtGui.QApplication.UnicodeUTF8))
        self.radioSetLDID.setText(QtGui.QApplication.translate("EncodingFixerDialogBase", "Set LDID", None, QtGui.QApplication.UnicodeUTF8))
        self.radioSetCPG.setText(QtGui.QApplication.translate("EncodingFixerDialogBase", "SET CPG file", None, QtGui.QApplication.UnicodeUTF8))
        self.radioClearLDID.setText(QtGui.QApplication.translate("EncodingFixerDialogBase", "Clear LDID and delete CPG file", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
