# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgencodingfixerbase.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EncodingFixerDialogBase(object):
    def setupUi(self, EncodingFixerDialogBase):
        EncodingFixerDialogBase.setObjectName("EncodingFixerDialogBase")
        EncodingFixerDialogBase.resize(548, 409)
        EncodingFixerDialogBase.setMinimumSize(QtCore.QSize(540, 400))
        EncodingFixerDialogBase.setMaximumSize(QtCore.QSize(600, 550))
        EncodingFixerDialogBase.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/shapefile_encoding_fixer/encoding_fixer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EncodingFixerDialogBase.setWindowIcon(icon)
        EncodingFixerDialogBase.setWhatsThis("")
        self.gridLayout_4 = QtWidgets.QGridLayout(EncodingFixerDialogBase)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(EncodingFixerDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.groupInfo = QtWidgets.QGroupBox(EncodingFixerDialogBase)
        self.groupInfo.setObjectName("groupInfo")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupInfo)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelInfo1 = QtWidgets.QLabel(self.groupInfo)
        self.labelInfo1.setObjectName("labelInfo1")
        self.gridLayout_2.addWidget(self.labelInfo1, 0, 0, 1, 1)
        self.labelInfo2 = QtWidgets.QLabel(self.groupInfo)
        self.labelInfo2.setObjectName("labelInfo2")
        self.gridLayout_2.addWidget(self.labelInfo2, 1, 0, 1, 1)
        self.labelFile = QtWidgets.QLabel(self.groupInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFile.sizePolicy().hasHeightForWidth())
        self.labelFile.setSizePolicy(sizePolicy)
        self.labelFile.setObjectName("labelFile")
        self.gridLayout_2.addWidget(self.labelFile, 0, 1, 1, 1)
        self.labelInfo3 = QtWidgets.QLabel(self.groupInfo)
        self.labelInfo3.setObjectName("labelInfo3")
        self.gridLayout_2.addWidget(self.labelInfo3, 2, 0, 1, 1)
        self.labelLDID = QtWidgets.QLabel(self.groupInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLDID.sizePolicy().hasHeightForWidth())
        self.labelLDID.setSizePolicy(sizePolicy)
        self.labelLDID.setObjectName("labelLDID")
        self.gridLayout_2.addWidget(self.labelLDID, 1, 1, 1, 1)
        self.labelCPG = QtWidgets.QLabel(self.groupInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCPG.sizePolicy().hasHeightForWidth())
        self.labelCPG.setSizePolicy(sizePolicy)
        self.labelCPG.setObjectName("labelCPG")
        self.gridLayout_2.addWidget(self.labelCPG, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupInfo, 1, 0, 1, 4)
        self.buttonFile = QtWidgets.QPushButton(EncodingFixerDialogBase)
        self.buttonFile.setMinimumSize(QtCore.QSize(48, 0))
        self.buttonFile.setObjectName("buttonFile")
        self.gridLayout.addWidget(self.buttonFile, 0, 3, 1, 1)
        self.comboLayer = QtWidgets.QComboBox(EncodingFixerDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboLayer.sizePolicy().hasHeightForWidth())
        self.comboLayer.setSizePolicy(sizePolicy)
        self.comboLayer.setMinimumSize(QtCore.QSize(220, 0))
        self.comboLayer.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.comboLayer.setObjectName("comboLayer")
        self.gridLayout.addWidget(self.comboLayer, 0, 2, 1, 1)
        self.groupFix = QtWidgets.QGroupBox(EncodingFixerDialogBase)
        self.groupFix.setObjectName("groupFix")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupFix)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 5, 0, 1, 2)
        self.labelMethodDescription = QtWidgets.QLabel(self.groupFix)
        self.labelMethodDescription.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMethodDescription.sizePolicy().hasHeightForWidth())
        self.labelMethodDescription.setSizePolicy(sizePolicy)
        self.labelMethodDescription.setWordWrap(True)
        self.labelMethodDescription.setOpenExternalLinks(True)
        self.labelMethodDescription.setObjectName("labelMethodDescription")
        self.gridLayout_3.addWidget(self.labelMethodDescription, 4, 0, 1, 2)
        self.radioSetLDID = QtWidgets.QRadioButton(self.groupFix)
        self.radioSetLDID.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioSetLDID.sizePolicy().hasHeightForWidth())
        self.radioSetLDID.setSizePolicy(sizePolicy)
        self.radioSetLDID.setObjectName("radioSetLDID")
        self.gridLayout_3.addWidget(self.radioSetLDID, 1, 0, 1, 1)
        self.comboEncodingLDID = QtWidgets.QComboBox(self.groupFix)
        self.comboEncodingLDID.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboEncodingLDID.sizePolicy().hasHeightForWidth())
        self.comboEncodingLDID.setSizePolicy(sizePolicy)
        self.comboEncodingLDID.setEditable(False)
        self.comboEncodingLDID.setObjectName("comboEncodingLDID")
        self.gridLayout_3.addWidget(self.comboEncodingLDID, 1, 1, 1, 1)
        self.radioSetCPG = QtWidgets.QRadioButton(self.groupFix)
        self.radioSetCPG.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioSetCPG.sizePolicy().hasHeightForWidth())
        self.radioSetCPG.setSizePolicy(sizePolicy)
        self.radioSetCPG.setObjectName("radioSetCPG")
        self.gridLayout_3.addWidget(self.radioSetCPG, 2, 0, 1, 1)
        self.comboEncodingCPG = QtWidgets.QComboBox(self.groupFix)
        self.comboEncodingCPG.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboEncodingCPG.sizePolicy().hasHeightForWidth())
        self.comboEncodingCPG.setSizePolicy(sizePolicy)
        self.comboEncodingCPG.setObjectName("comboEncodingCPG")
        self.gridLayout_3.addWidget(self.comboEncodingCPG, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupFix)
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 6, 0, 1, 2)
        self.radioClearLDID = QtWidgets.QRadioButton(self.groupFix)
        self.radioClearLDID.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioClearLDID.sizePolicy().hasHeightForWidth())
        self.radioClearLDID.setSizePolicy(sizePolicy)
        self.radioClearLDID.setObjectName("radioClearLDID")
        self.gridLayout_3.addWidget(self.radioClearLDID, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.groupFix, 2, 0, 1, 4)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.label.setBuddy(self.comboLayer)

        self.retranslateUi(EncodingFixerDialogBase)
        self.buttonBox.rejected.connect(EncodingFixerDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(EncodingFixerDialogBase)
        EncodingFixerDialogBase.setTabOrder(self.comboLayer, self.buttonFile)
        EncodingFixerDialogBase.setTabOrder(self.buttonFile, self.radioClearLDID)
        EncodingFixerDialogBase.setTabOrder(self.radioClearLDID, self.radioSetLDID)
        EncodingFixerDialogBase.setTabOrder(self.radioSetLDID, self.comboEncodingLDID)
        EncodingFixerDialogBase.setTabOrder(self.comboEncodingLDID, self.radioSetCPG)
        EncodingFixerDialogBase.setTabOrder(self.radioSetCPG, self.comboEncodingCPG)

    def retranslateUi(self, EncodingFixerDialogBase):
        _translate = QtCore.QCoreApplication.translate
        EncodingFixerDialogBase.setWindowTitle(_translate("EncodingFixerDialogBase", "Fix Shapefile Encoding"))
        self.label.setText(_translate("EncodingFixerDialogBase", "Shapefile"))
        self.groupInfo.setTitle(_translate("EncodingFixerDialogBase", "Layer info"))
        self.labelInfo1.setText(_translate("EncodingFixerDialogBase", "Dbf File:"))
        self.labelInfo2.setText(_translate("EncodingFixerDialogBase", "LDID byte:"))
        self.labelFile.setText(_translate("EncodingFixerDialogBase", "--"))
        self.labelInfo3.setText(_translate("EncodingFixerDialogBase", "CPG file:"))
        self.labelLDID.setText(_translate("EncodingFixerDialogBase", "--"))
        self.labelCPG.setText(_translate("EncodingFixerDialogBase", "--"))
        self.buttonFile.setText(_translate("EncodingFixerDialogBase", "..."))
        self.groupFix.setTitle(_translate("EncodingFixerDialogBase", "Fix encoding declaration"))
        self.labelMethodDescription.setText(_translate("EncodingFixerDialogBase", "Description placeholder..."))
        self.radioSetLDID.setText(_translate("EncodingFixerDialogBase", "Set LDID"))
        self.radioSetCPG.setText(_translate("EncodingFixerDialogBase", "SET CPG file"))
        self.radioClearLDID.setText(_translate("EncodingFixerDialogBase", "Clear LDID and delete CPG file"))

from .resources_rc import *
